### ISSUE TITLE
Update to new gradle configuration names

### ISSUE THREAD

**Issue by ericbottard** [jerzykrlk/jcstress-gradle-plugin#21]
The plugin uses deprecated gradle APIs and concepts, in particular when it comes to configuration names (eg compile vs implementation, etc).
This prevents projects that use the jcstress-gradle-plugin from using the correct names as well, as gradle provides compatibility in one direction, but not the other.

**Comment by ericbottard** [comment]
I have a fix for this and will open a PR for review.

**Comment by jerzykrlk** [comment]
Hi Eric,

As in my comment [here](https://github.com/jerzykrlk/jcstress-gradle-plugin/pull/22#issuecomment-682156457) - would you be able to rebase to the current master so that the branch builds cleanly with Travis?

**Comment by ericbottard** [comment]
Of course, yes. Sorry for the late reply

**Comment by ericbottard** [comment]
Awesome! Thanks for merging this. Let me know if you would be able to perform a release of the plugin, so that we could consume the changes.

**Comment by jerzykrlk** [comment]
Okay, I've just released - the version is now 0.8.4. Thank you again!
