### ISSUE TITLE
jcstress related classes end up in project jar

### ISSUE THREAD

**Issue by ericbottard** [jerzykrlk/jcstress-gradle-plugin#28]
The jcstressJar task doesn't override the jar name (or use a classifier, an even better solution to this problem) so the generated jar ends up overwriting the regular project jar. As a consequence, test related classes often end up being part of published artifacts. Even worse, some other classes/resources could be lost if users customized the way they want their jar built.

See https://github.com/reactor/reactor-core/issues/2400

**Comment by jerzykrlk** [comment]
Hi Eric,

Thanks for reporting. I've never honestly used this feature, I just copied it over from the JMH plugin, way in the past. I'm glad to see someone is using it.

I will try to fix it - I'm not sure about the timelines, but I will do my best.

Thanks again,

**Comment by jerzykrlk** [comment]
Okay, it turned out to be less trivial because just `jcstressJarTask.getArchiveClassifier().set("jcstress")` doesn't seem to work. Just let me check it in more detail - see this one: https://github.com/jerzykrlk/jcstress-gradle-plugin/pull/31

**Comment by jerzykrlk** [comment]
Actually, the archive classifier works fine. It was my IDE and my own Gradle build configuration that was wrong.

Fixed, published - please try version 0.8.5.

**Comment by ericbottard** [comment]
Works good. Thanks!
