### ISSUE TITLE
Update jcstress-core

### ISSUE THREAD

**Issue by leventov** [jerzykrlk/jcstress-gradle-plugin#3]
Currently the plugin builds on jcstress sources dated 2015.07. There are many changes to the jcstress repo since that.

**Comment by jerzykrlk** [comment]
Hi,
I'll try to build the most recent Java 8-compatible jcstress and see if works without changing the plugin itself. This week, I hope...

**Comment by leventov** [comment]
I was able to
1. build latest jcstress (from repo) with Java 9 b124, but test were failing to build, so I just removed them, to build only core and code-gen.
2. build your plagin (latest from repo) with 1.0-snapshot jcstress (built on step 1) hard coded in JcstressPluginExtension.groovy
3. build my test using the version of the plugin, built on step 2, with mavenLocal()

However, running tests produced by this led to some strange crashes.

**Comment by jerzykrlk** [comment]
I've played around with newer jcstress and it looks like some jcstress concepts have changed. So it's going to take some more time.

I'll try to assemble the [[d1ed559](http://hg.openjdk.java.net/code-tools/jcstress/rev/d1ed559a1b55) version.

**Comment by jerzykrlk** [comment]
Ok, I've released a new version just now. 

Can you verify everything works fine?

**Comment by jerzykrlk** [comment]
Ok, I found a bug with 0.7.0 - only unforked runs worked. I've just released and checked the 0.7.1 version - seems to work fine with forks, too.

I've assembled the d1ed559 version, but jcstress required some code changes from my side to make it work with Gradle.
