### ISSUE TITLE
jcstress.jcstressDependency configuration doesn't work

### ISSUE THREAD

**Issue by leventov** [jerzykrlk/jcstress-gradle-plugin#4]
I try to specify custom jcstressDependency via
```groovy
jcstress {
    jcstressDependency 'org.openjdk.jcstress:jcstress-core:1.0-SNAPSHOT'
}
```

But `compileJcstressJava` task still adds `modules-2\files-2.1\com.github.erizo.gradle\jcstress-core\1.0-20150729205107\e72a014e334393da09e07ea3c1aa58af345b643d\jcstress-core-1.0-20150729205107.jar` file to the classpath.

**Comment by jerzykrlk** [comment]
Hi,
I've just releases a 0.6.1 version that should fix this. Can you have a look before I update the docs? Unfortunately, I haven't had time to produce & release another build of jcstress just yet.

**Comment by jerzykrlk** [comment]
It turned out that the changes in jcstress required changes in the plugin itself. 

I think I will remove or just deprecate this option in future - it is very unlikely that an arbitrary jcstress build is going to work well.
